github_username: DEEDS99
default_branch: main
auto_deploy: true

hosting_platforms:
  vercel:
    enabled: false
    deploy_hook_url: ""   # paste your Vercel Deploy Hook URL
  render:
    enabled: false
    service_id: "dpg-d2c26hruibrs738263l0-a"        
  netlify:
    enabled: false
    deploy_hook_url: ""   # paste your Netlify Build Hook URL

commit_message_templates:
  - "ğŸš€ Auto-deploy: {description}"
  - "ğŸ“ Update: {description}"
  - "ğŸ”§ Fix: {description}"
  - "âœ¨ Feature: {description}"
